name: 🎯 Sprint Backlog Epic
description: 스프린트 백로그 에픽 생성
title: "[BE] "
labels:
  - part:backend
  - epic
projects:
  - 100-hours-a-week/314

body:
  - type: markdown
    attributes:
      value: |
        ## 스프린트 백로그 에픽
        에픽의 전체적인 업무 항목과 일정을 관리합니다.

  - type: textarea
    id: tasks
    attributes:
      label: 업무 항목
      description: 에픽에 포함된 업무들을 표 형식으로 작성해주세요
      placeholder: |
        | 이름 (업무 항목)                     | 기간                               | 담당자 |
        |--------------------------------------|------------------------------------|--------|
        | [업무 이름 - 단계]                   | 2099년 00월 00일 → 2099년 00월 00일 | [이름] |
        | [업무 이름 - 단계]                   | 2099년 00월 00일 → 2099년 00월 00일 | [이름] |
        | [업무 이름 - 단계]                   | 2099년 00월 00일 → 2099년 00월 00일 | [이름] |
        | [업무 이름 - 단계]                   | 2099년 00월 00일 → 2099년 00월 00일 | [이름] |
      value: |
        | 이름 (업무 항목)                     | 기간                               | 담당자 |
        |--------------------------------------|------------------------------------|--------|
        | [업무 이름 - 단계]                   | 2099년 00월 00일 → 2099년 00월 00일 | [이름] |
        | [업무 이름 - 단계]                   | 2099년 00월 00일 → 2099년 00월 00일 | [이름] |
        | [업무 이름 - 단계]                   | 2099년 00월 00일 → 2099년 00월 00일 | [이름] |
        | [업무 이름 - 단계]                   | 2099년 00월 00일 → 2099년 00월 00일 | [이름] |
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: 예상되는 리스크
      description: 이 에픽을 진행하면서 예상되는 리스크를 작성해주세요
      placeholder: |
        - API 응답 시간이 느릴 수 있음
        - 외부 라이브러리 의존성 문제
    validations:
      required: false

  - type: textarea
    id: challenges
    attributes:
      label: 어려움이 있었던 부분
      description: 진행 중 겪은 어려움과 해결 과정을 작성해주세요
      placeholder: |
        1. 제목
        - 문제 : 
        - 해결 : 
        - 근거 : 
        - 성과 :
      value: |
        1. 제목
        - 문제 : 
        - 해결 : 
        - 근거 : 
        - 성과 :
    validations:
      required: false