name: ✨ Feature
description: 기능 추가 / 개선
title: "[FEAT] "
labels:
  - feature
projects:
  - 100-hours-a-week/TEAM 10

body:
  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 추가하거나 개선하고 싶은 기능을 설명해주세요.
      placeholder: JWT 토큰 재발급 API 추가
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: 작업 내용
      placeholder: |
        - [ ] API 설계
        - [ ] 테스트 코드 작성
        - [ ] 문서 정리
